// Explicitly list all props that shouldn't be forwarded to DOM
export const commonStyledProps = new Set([
  // Debug Options
  'debug',
  'debugBGColor',

  // Layout & Sizing
  'fullWidth',
  'fullHeight',
  'minWidth',
  'maxWidth',
  'minHeight',
  'maxHeight',
  'width',
  'height',
  'padding',
  'margin',
  'marginTop',
  'marginRight',
  'marginBottom',
  'marginLeft',
  'alignSelf',
  'gap',
  'flexDirection',
  'flex',
  'aspectRatio',
  'float',
  'shapeOutside',

  // Display & Position
  'position',
  'display',
  'alignItems',
  'justifyContent',
  'overflow',
  'overflowX',
  'overflowY',
  'boxSizing',

  // Scrollbar Customization
  'scrollbarColor',
  'scrollbarGutter',
  'scrollbarWidth',
  'scrollbarHeight',
  'scrollbarTrackBackground',
  'scrollbarThumbBackground',
  'scrollbarThumbBackgroundColor',
  'scrollbarThumbHoverBackground',
  'scrollbarThumbHoverBackgroundColor',
  'scrollbarThumbActiveBackground',
  'scrollbarThumbActiveBackgroundColor',
  'scrollbarThumbBorder',
  'scrollbarThumbBorderRadius',
  'scrollbarThumbBackgroundClip',

  // Visual Style
  'backgroundColor',
  'bgColor',
  'background',
  'backgroundImage',
  'backgroundPosition',
  'backgroundRepeat',
  'backgroundSize',
  'borderRadius',
  'borderWidth',
  'borderStyle',
  'borderColor',
  'border',
  'borderTop',
  'borderRight',
  'borderBottom',
  'borderLeft',
  'boxShadow',
  'opacity',
  'filter',
  'backdropFilter',

  // Typography
  'color',
  'fontSize',
  'fontWeight',
  'fontFamily',
  'textAlign',
  'letterSpacing',
  'lineHeight',
  'textWrap',
  'textTransform',
  'textStroke',
  'textShadow',
  'userSelect',
  'whiteSpace',
  'hyphens',
  'selectionTextColor',
  'selectionBackgroundColor',

  // Transitions & Animations
  'transition',
  'transform',
  'transformOrigin',
  'animation',
  'isThemeTransition',

  // Hover States
  'hoverBackgroundColor',
  'hoverColor',
  'hoverBorderColor',
  'hoverBorderWidth',
  'hoverBorderStyle',
  'hoverBorderRadius',
  'hoverTransform',
  'hoverBoxShadow',
  'hoverBorder',
  'hoverBackdropFilter',

  // Focus States
  'focusOutline',
  'focusOutlineOffset',
  'focusBorderColor',
  'focusBoxShadow',

  // Active States
  'activeBackgroundColor',
  'activeColor',
  'activeBorder',
  'activeBorderColor',
  'activeBorderWidth',
  'activeBorderStyle',
  'activeBorderRadius',
  'activeTransform',
  'activeBoxShadow',

  // Positioning
  'top',
  'right',
  'bottom',
  'left',
  'zIndex',

  // Other
  'cursor',
  'pointerEvents',
  'clipPath',
  'maskImage',
  'maskSize',
  'maskRepeat',
  'maskPosition'
]);